<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Moe" failures="1" tests="3" name="Test2" time="29.039" errors="0" timestamp="2024-05-28T03:18:52 EDT">
  <testcase classname="automate.tests.ErrorValidations" name="loginErrorValidation" time="0.898">
    <skipped/>
  </testcase> <!-- loginErrorValidation -->
  <testcase classname="automate.tests.ErrorValidations" name="loginErrorValidation" time="0.791">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at automate.tests.ErrorValidations.loginErrorValidation(ErrorValidations.java:18)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
... Removed 19 stack frames]]>
    </failure>
  </testcase> <!-- loginErrorValidation -->
  <testcase classname="automate.tests.ErrorValidations" name="productErrorValidation" time="4.971"/>
</testsuite> <!-- Test2 -->
